# Generated by Django 3.2.6 on 2021-08-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Password')),
            ],
        ),
    ]
